"""remove unique constraint from centre_id

Revision ID: 7093d91851e0
Revises: e494f7fd68e3
Create Date: 2025-10-19 23:44:50.918465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7093d91851e0'
down_revision = 'e494f7fd68e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('therapists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_therapists_centre_id'))
        batch_op.create_index(batch_op.f('ix_therapists_centre_id'), ['centre_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('therapists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_therapists_centre_id'))
        batch_op.create_index(batch_op.f('ix_therapists_centre_id'), ['centre_id'], unique=1)

    # ### end Alembic commands ###
